package com.brainplow.ogrespace.models

data class PropertyModel(
    val active_bool: Boolean? = null,
    val address: String? = null,
    val city: String? = null,
    val contact_no: Any? = null,
    val country: String? = null,
    val created: String? = null,
    val description: String? = null,
    val destag: String? = null,
    val features: Any? = null,
    val id: Int? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val mappedbool: Boolean? = null,
    val one_pic: String? = null,
    val overview: Any? = null,
    val overviewtag: Any? = null,
    val pic_url: String? = null,
    val post_type: String? = null,
    val posted_date: Any? = null,
    val presented_company: Any? = null,
    val presented_name: String? = null,
    val price: Double? = null,
    val price_type: String? = null,
    val property_area: Double? = null,
    val property_id: Int? = null,
    val property_link: String? = null,
    val property_title: String? = null,
    val property_type: String? = null,
    val services: String? = null,
    val state: String? = null,
    val subspace_status: Boolean? = null,
    val user_id: Int? = null,
    val zipcode: String? = null
)