package com.brainplow.ogrespace.models

data class PropertyModel(
    var active_bool: Boolean? = null,
    var address: String? = null,
    var city: String? = null,
    var contact_no: Any? = null,
    var country: String? = null,
    var created: String? = null,
    var description: String? = null,
    var destag: String? = null,
    var features: Any? = null,
    var id: Int? = null,
    var latitude: Double? = null,
    var longitude: Double? = null,
    var mappedbool: Boolean? = null,
    var one_pic: String? = null,
    var created_at: String? = null,
    var user: Int? = null,
    var overview: Any? = null,
    var overviewtag: Any? = null,
    var pic_url: String? = null,
    var post_type: String? = null,
    var posted_date: Any? = null,
    var presented_company: Any? = null,
    var presented_name: String? = null,
    var price: Double? = null,
    var price_type: String? = null,
    var property_area: Double? = null,
    var property_id: Int? = null,
    var property_link: String? = null,
    var property_title: String? = null,
    var property_type: String? = null,
    var services: String? = null,
    var state: String? = null,
    var subspace_status: Boolean? = null,
    var user_id: Int? = null,
    var zipcode: String? = null
){

}